### ISSUE TITLE
a sore point

### ISSUE THREAD

**Issue by kimchanghee94** [JoeriSmits/GoogleAnything#2]
If you click after searching, it would be better to open inside instead of opening a new window outside of vscode.

**Comment by JoeriSmits** [comment]
Hi @kimchanghee94 ,

Current behaviour is that the results are shown in a new window which splits the current workspace into two. Would you like to see the results showing on the main focussed window? 
I can make a setting out of this.

**Comment by JoeriSmits** [comment]
Closing this since there is no response
